name: Client
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

permissions:
  contents: read

jobs:
  build-client:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'
      - name: Install dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
          dir: client
      - name: Run tests
        uses: borales/actions-yarn@v4.2.0
        env: 
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
        with:
          cmd: build
          dir: client
      - name: version
        working-directory: client
        run: npm version patch --workspaces
      - name: publish
        working-directory: client
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
