name: Build lowcoder dev image

on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lowcoder from 'dev' branch
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Get commit short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Docker Buildx with cloud driver
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "lowcoderorg/lowcoder-cloud-builder"
      - name: Build and push the all-in-one image
        uses: docker/build-push-action@v6
        env:
          NODE_ENV: production
        with:
          file: ./deploy/docker/Dockerfile
          build-args: |
            REACT_APP_ENV=production
            REACT_APP_COMMIT_ID="dev #${SHORT_SHA}"
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: lowcoderorg/lowcoder-ce:dev

